# Generated by Django 6.1 on 2026-08-28 08:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My Shop', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Fine Gold & Silver Jewellery', help_text='Short line shown under the shop name on receipts.', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Shown at the top of printed receipts. Square images work best.', null=True, upload_to='shop/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('receipt_note', models.CharField(blank=True, default='Thank you for shopping with us!', help_text='Short thank-you / policy line shown at the bottom of receipts.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('metal_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('OTHER', 'Other')], default='GOLD', max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the item (optional).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_unit', models.CharField(choices=[('GRAM', 'Grams'), ('TOLA', 'Tola')], default='GRAM', max_length=6)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU / Item Code')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='What the shop paid to acquire this item, per unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Buy Price (Cost)')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Standard selling price per unit, shown to customers.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price')),
                ('description', models.TextField(blank=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sent_to', models.CharField(max_length=200, verbose_name='Sent To (Karigar / Workshop)')),
                ('sent_to_contact', models.CharField(blank=True, max_length=50)),
                ('issue_description', models.TextField(blank=True, help_text='Reason / details of repair')),
                ('sent_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Out for Repair'), ('RECEIVED', 'Received Back')], default='SENT', max_length=10)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_logged', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='inventory.product')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text="Selling price per unit for this transaction (defaults to the product's sale price).", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional flat discount for this sale.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Automatically calculated: (unit price x quantity) - discount.', max_digits=12)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.product')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
