# Generated by Django 5.2.17 on 2026-08-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
    ]
