# Generated by Django 6.1 on 2026-08-31 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopsettings',
            options={'verbose_name_plural': 'Shop Settings'},
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Buy Price (Cost)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='repairrecord',
            name='issue_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='receipt_note',
            field=models.CharField(blank=True, default='Thank you for shopping with us!', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='tagline',
            field=models.CharField(blank=True, default='Fine Gold & Silver Jewellery', max_length=200),
        ),
    ]
